using System;
using System.Collections.Generic;
using System.IO;
using Bali.Constants;
using Bali.IO;
using Bali.SourceGeneration;

namespace Bali.Attributes.Readers
{
    /// <summary>
    /// Provides a basic implementation of the <see cref="IJvmAttributeReaderFacade"/> contract with
    /// modularity in mind, so custom non-standard attributes can be processed if needed.
    /// </summary>
    public class JvmAttributeReaderFacade : IJvmAttributeReaderFacade
    {
        private readonly IBigEndianReader _reader;
        private readonly ConstantPool _constantPool;
        private readonly Dictionary<string, IJvmAttributeReader> _concreteReaders;

        private static readonly DefaultJvmAttributeReader DefaultJvmAttributeReader = new();

        /// <summary>
        /// Creates a new <see cref="JvmAttributeReaderFacade"/>.
        /// </summary>
        /// <param name="reader">The input <see cref="Stream"/> to read data from.</param>
        /// <param name="constantPool">The <see cref="ConstantPool"/>.</param>
        public JvmAttributeReaderFacade(IBigEndianReader reader, ConstantPool constantPool)
        {
            _reader = reader;
            _constantPool = constantPool;
            _concreteReaders = new Dictionary<string, IJvmAttributeReader>
            {
                ["Code"] = new CodeAttributeReader(this)
            };
            
            AutoGeneratedReaders.AddToCache(this);
        }

        /// <inheritdoc />
        public IJvmAttributeReader this[string name]
        {
            get => _concreteReaders.TryGetValue(name, out var value)
                ? value
                : DefaultJvmAttributeReader;
            set
            {
                if (name != value.Name)
                    throw new ArgumentException(nameof(name));
                
                _concreteReaders[name] = value;
            }
        }

        /// <inheritdoc />
        public JvmAttribute ReadAttribute()
        {
            ushort nameIndex = _reader.ReadU2();
            string name = GetName(nameIndex);

            return this[name].Read(_reader, nameIndex);
        }

        private string GetName(ushort nameIndex)
        {
            var constant = _constantPool[nameIndex];
            if (constant is not Utf8Constant { Value: { } name })
                throw new ArgumentException(nameof(nameIndex));

            return name;
        }
    }
}