using Bali.SourceGeneration;

namespace Bali.Attributes
{
    /// <summary>
    /// An attribute which indicates that the member is generated by the compiler.
    /// </summary>
    [AutoFactory]
    [AutoBuilder]
    public sealed class SyntheticAttribute : JvmAttribute
    {
        /// <summary>
        /// Creates a new <see cref="SignatureAttribute"/>.
        /// </summary>
        /// <param name="nameIndex">The index into the <see cref="ConstantPool"/> representing the name of the attribute.</param>
        public SyntheticAttribute(ushort nameIndex)
            : base(nameIndex)
        {
        }
    }
}