using System;
using System.Collections.Generic;
using Bali.Constants;
using Bali.IO;
using Bali.SourceGeneration;

namespace Bali.Attributes.Writers
{
    /// <summary>
    /// Provides a default implementation of the <see cref="IJvmAttributeDirector"/> contract, with
    /// modularity in mind, so non-standard attributes can be processed.
    /// </summary>
    public sealed class JvmAttributeDirector : IJvmAttributeDirector
    {
        private readonly ConstantPool _constantPool;
        private readonly Dictionary<string, IJvmAttributeWriter> _writers;

        private static readonly DefaultJvmAttributeWriter DefaultJvmAttributeWriter = new();

        /// <summary>
        /// Creates a new <see cref="JvmAttributeDirector"/>.
        /// </summary>
        /// <param name="constantPool">The <see cref="ConstantPool"/> to resolve the name of attributes from.</param>
        public JvmAttributeDirector(ConstantPool constantPool)
        {
            _constantPool = constantPool;
            _writers = new Dictionary<string, IJvmAttributeWriter>
            {
                ["Code"] = new CodeAttributeWriter(this),
                ["StackMapTable"] = new StackMapTableAttributeWriter(this)
            };

            AutoGeneratedWriters.AddToCache(this);
        }

        /// <inheritdoc />
        public IJvmAttributeWriter this[string name]
        {
            get => _writers.TryGetValue(name, out var builder)
                ? builder
                : DefaultJvmAttributeWriter;
            set
            {
                if (name != value.Name)
                    throw new ArgumentException(nameof(name));
                
                _writers[name] = value;
            }
        }

        /// <inheritdoc />
        public void WriteAttribute(JvmAttribute attribute, IBigEndianWriter writer)
        {
            string name = GetName(attribute.NameIndex);
            var handler = this[name];
            
            handler.WriteName(attribute, writer);
            
            using var segment = writer.WithU4Length();
            handler.WriteBody(attribute, segment);
        }

        private string GetName(ushort nameIndex)
        {
            var constant = _constantPool[nameIndex];
            if (constant is not Utf8Constant { Value: { } name })
                throw new ArgumentException(nameof(nameIndex));
            
            return name;
        }
    }
}